// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'

    show defaultTargetPlatform, kIsWeb, TargetPlatform;
/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
/// 
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrZxF6FdK7y1d2ahr7iNZyZvujQSyouiI',
    appId: '1:204177934648:web:3c1b120f845a0c8203d9cd',
    messagingSenderId: '204177934648',
    projectId: 'micos-bikeshop',
    authDomain: 'micos-bikeshop.firebaseapp.com',
    storageBucket: 'micos-bikeshop.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAy-3iQ_1ID2gnFgWk4MpWhoITf72BDI8I',
    appId: '1:468129765804:android:2514d26e259edfe9930209',
    messagingSenderId: '468129765804',
    projectId: 'my-micos-bikeshop',
    storageBucket: 'my-micos-bikeshop.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAITKChlzgJ343PxDTMpMTMljR5XXcS2CI',
    appId: '1:468129765804:ios:325a0ed5147b05ec930209',
    messagingSenderId: '468129765804',
    projectId: 'my-micos-bikeshop',
    storageBucket: 'my-micos-bikeshop.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKgfyZt3UCMES7XtsI6zUNjk_sl8QlwEo',
    appId: '1:204177934648:ios:cd844b639eddee3c03d9cd',
    messagingSenderId: '204177934648',
    projectId: 'micos-bikeshop',
    storageBucket: 'micos-bikeshop.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCrZxF6FdK7y1d2ahr7iNZyZvujQSyouiI',
    appId: '1:204177934648:web:8aa50f92b9478dbe03d9cd',
    messagingSenderId: '204177934648',
    projectId: 'micos-bikeshop',
    authDomain: 'micos-bikeshop.firebaseapp.com',
    storageBucket: 'micos-bikeshop.firebasestorage.app',
  );
}